### ISSUE TITLE
Crypto test 23 fails in CI

### ISSUE THREAD

**Issue by karlb** [karlb/sqlite-sqlean#4]
See https://github.com/karlb/sqlite-sqlean/actions/runs/4156032283/jobs/7189532753#step:5:71

It works locally for me, but there is no reason the results should differ.

**Comment by karlb** [comment]
The result is `5B2BEAC7EDFC3D105F66435F0DDF6C8BA1A07FF784229BF07AC92A88EB4756EC` (see https://github.com/karlb/sqlite-sqlean/actions/runs/4156335384/jobs/7190062206#step:5:54) instead of the expected `BA7816BF8F01CFEA414140DE5DAE2223B00361A396177A9CB410FF61F20015AD`.

**Comment by karlb** [comment]
The problem only happens for sha256, it is ok for all other crypto functions. But for sha256, the results are wrong in CI for all inputs but the empty string.

**Comment by cldellow** [comment]
The test failures are odd. I get the `BA7...` result using the official binaries on linux x86.

Is the failure for all SHA-2 functions, like SHA-384 and SHA-512, or only SHA-256?

Is it possibly an endianness issue of some sort? The notes in [sha2.c](https://github.com/nalgeon/sqlean/blob/07549eb19e69ce8a3c9bd73c991853d753027d10/src/crypto/sha2.c#L61-L116) mention certain defines that must be present.

...but a quick skim looks like the build would fail if they were missing, not quietly do the wrong thing. Still, that might be worth confirming? That might explain why the empty string works, but non-empty values are odd.

**Comment by karlb** [comment]
> Is the failure for all SHA-2 functions, like SHA-384 and SHA-512, or only SHA-256?

No, it only happen for SHA-256 and only when building from source with the approach in the master branch. The official sqlean binaries do not show the problem.

So there must be something wrong with the build process. That could be because I abuse the python extension build process to build something that is not actually a python extension. But I would expect more severe problems or no problems at all, not such a subtle problem as this while all other extensions work fine.

**Comment by karlb** [comment]
It seems to be the optimization level of the compiler. Using `-O1` during the build (like sqlean does) avoids the problem. I'm not sure if that is a real solution, or if we are just lucky that it is not triggered in this case. I'm not too familiar with the details of optimization levels. I could imagine the following cases:
* It is a bug in the crypto code which is only triggered when compiled in specific ways
* The compiler thinks that the optimization is safe, but it is not (compiler bug)
* There is a good reason why the code must not be optimized stronger than `-O1` (I don't know what such a reason would be).

Also, I'm not sure where the specific version of the crypto code comes from. It seems to be derived from https://aarongifford.com/computers/sha.html, which uses `-O2` in an example.

@nalgeon, do you have any input on this?

**Comment by nalgeon** [comment]
I'd like to blame the compiler, but something tells me the problem is more likely in the crypto code :) But compiling with `-O1` gives a reasonable workaround, so I left it at that for now. Feel free to investigate the problem further if you have the time and energy.
